In [1]:
# Install Numpy package from python library
!pip install numpy

In [2]:
# Importing numpy
import numpy as np

In [3]:
# Creating an one-dimensional array
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
# DataType of an array elements
arr1.dtype

dtype('int32')

In [6]:
# Creating two dimensional array
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# To get the shape of the matrix
np.shape(arr2)

(2, 3)

In [8]:
# Creating three dimensional array
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]]])

In [9]:
# Finding the dimensions of an array
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [10]:
# Array with all zeroes
arr4 = np.zeros(5)
arr4

array([0., 0., 0., 0., 0.])

In [11]:
# Array with all ones
arr5 = np.ones(5)
arr5

array([1., 1., 1., 1., 1.])

In [12]:
# Print numbers evenly within the range
arr6 = np.arange(10,100,5)
arr6

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [13]:
# Print number evenly within the interval
arr7 = np.linspace(10,100,5)
arr7

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [14]:
# To get the random values
np.random.random()

0.7192467565017968

In [15]:
# To get n random values
np.random.random(10)

array([0.23177193, 0.95082356, 0.98903205, 0.13112658, 0.43251399,
       0.22503914, 0.55979642, 0.12824209, 0.27504777, 0.37562724])

In [16]:
# Gives the random integer value every time below 100 when executes
np.random.randint(100)

48

In [17]:
# Gives the random integer value within the given range
np.random.randint(5,10)

9

In [18]:
# Gives the 10 random values within the range
np.random.randint(1,100,10)

array([14, 63, 68, 24, 12, 17, 86, 71, 70, 51])

In [19]:
# Create an identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
# Create an identity matrix with int data type
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [21]:
# Converting 3x2 matrix to 2x3 matrix
arr8 = np.array([[1,2],[3,4],[5,6]])
print("3 x 2 matrix")
print(arr8)
print("2 x 3 matrix")
print(arr8.reshape(2,3))

3 x 2 matrix
[[1 2]
 [3 4]
 [5 6]]
2 x 3 matrix
[[1 2 3]
 [4 5 6]]


In [22]:
# Concatenation - combining the arrays
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
np.concatenate((a1,a2))

array([1, 2, 3, 4, 5, 6])

In [23]:
# Split - splits the array into parts
arr = np.array([1,2,3,4,5,6])
np.split(arr,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [24]:
# Slicing - Getting required values from array
arr8 = np.array([1,2,3,4,5,6,7,8,9])
arr8

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr8[1:5]

array([2, 3, 4, 5])

In [26]:
arr8[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr8[-3:-1]

array([7, 8])

In [28]:
# Mathematical operations
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [29]:
np.sqrt(10)

3.1622776601683795

In [30]:
np.log(2)

0.6931471805599453

In [31]:
np.abs(-10)

10

In [32]:
np.ceil(2.5)

3.0

In [33]:
np.floor(2.5)

2.0

In [34]:
np.round(2.7)

3.0

In [35]:
arr = np.array([1,2,3,4,5,6])
print(arr.sum())
print(arr.mean())
print(arr.min())
print(arr.max())
print(arr.argmin())
print(arr.argmax())
print(arr.std())
print(arr.var())

21
3.5
1
6
0
5
1.707825127659933
2.9166666666666665
